name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.101
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Build Number Generator
      uses: einaregilsson/build-number@v2
    - name: pack nuget
      run: dotnet pack /p:PackageVersion=0.0.2.${BUILD_NUMBER} --no-build --no-restore
    - name: push nuget
      run: dotnet push -s https://api.nuget.org/v3/index.json
